version: '3.8.0.1'

services:
  app:
    container_name: worktracker-web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_NOTIFICATION_APP_ID: app_HKKiWsalytaLP9Dd
        NEXT_PUBLIC_NOTIFICATION_PUBLIC_KEY: sk_AvDKMijNzNLat_QY4tBGIiic15ZVob274wEzo8hsxJ4CGRXOp0E26LO9BuY5pJYO
        NEXT_PUBLIC_NOTIFICATION_BASE_URL: https://vibemessage.sailorlabs.in/api
    restart: always
    ports:
      - "3100:3100"
    env_file:
      - .env
    environment:
      # Use the service name "db" for the database host within the docker network
      DATABASE_URL: postgresql://umangsailor:Umang6Sailor@192.168.1.2:5432/worktracker?schema=public
      NEXTAUTH_URL: https://worktracker.sailorlabs.in/
      NEXTAUTH_SECRET: work-time-tracker-super-secret-key-change-in-production
      AUTH_TRUST_HOST: true
      NEXT_PUBLIC_NOTIFICATION_APP_ID: app_HKKiWsalytaLP9Dd
      NEXT_PUBLIC_NOTIFICATION_PUBLIC_KEY: sk_AvDKMijNzNLat_QY4tBGIiic15ZVob274wEzo8hsxJ4CGRXOp0E26LO9BuY5pJYO
      NOTIFICATION_SECRET_KEY: sk_fAxYG808gSpbSRvvW2DhKBp_K4HOdtj3jKCDzRhBG31PZzNwIQlc1LOgWEkq1ohA
      NEXT_PUBLIC_NOTIFICATION_BASE_URL: https://vibemessage.sailorlabs.in/api
    # depends_on:
    #   - db
    networks:
      - worktracker-network

#   db:
#     container_name: worktracker-db
#     image: postgres:15-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: umangsailor
#       POSTGRES_PASSWORD: Umang6Sailor
#       POSTGRES_DB: worktracker
#     ports:
#       # Expose port so local tools (like Prisma Studio or pgAdmin) can connect if needed
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - worktracker-network

networks:
  worktracker-network:
    driver: bridge

# volumes:
#   postgres_data:
